mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句
    map-underscore-to-camel-case: true # 下划线命名映射到驼峰命名
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: QWOrwu197778
    url: jdbc:mysql://localhost:3306/ling_guang # 数据源 url
    username: root

# 设置日志级别
#logging:
#  level:
#    org:
#      mybatis: TRACE
